### ISSUE TITLE
Legion Mob Template Bug

### ISSUE THREAD

**Issue by Nachtmahr91** [Eve-of-Darkness/db-public#102]
Make the mob "Legion" and then make / mob name Legion.
Then look at / mob viewloot for what he has for a mob template.
Then restart the server and then see what he has again for a Mob template. If you create legion, he still has the normal mob template from Legion and after the server restart he has the mob template of "The Terrible" and "Flame of Volcanus".

**Comment by LRFalk01** [comment]
Legion was worked on by @rogersmith0. Closing this issue. It sounds like you're describing an issue w/ the mob slash commands which would be an issue w/ DOL not the database. Maybe discuss the issue on the forums.
