### ISSUE TITLE
Darkness Falls (Mobs)

### ISSUE THREAD

**Issue by Nachtmahr91** [Eve-of-Darkness/db-public#112]
- Molochian Tempter has the same problem as Legion had with the Loottemplate.
    Molochian Tempter owns the Loottemplate of The Terrible and Draco.

- The mobs in the entrance area, for example, the rats have a wrong level and should all be level 15.

- TThe Demoniac Familiar at the entrance of DF are wrong.
At the entrance ONLY have to be rats and the rats are ONLY Level 15.# The new Mob Model ID for this fix is: 568
    http://camelot.allakhazam.com/db/search.html?cmob=2822

- Lilispawn has the wrong level. The level should be 29 - 40.
    http://camelot.allakhazam.com/db/search.html?cmob=2968

- The Mob Chthonian Crawler is missing completely.
    http://camelot.allakhazam.com/db/search.html?cmob=3017

- The mob behemoth is missing completely. One is teleported to this mob when attacking Legion. Legion selects any person in the group and teleportes him to Behemoth.
    http://camelot.allakhazam.com/db/search.html?cmob=2862

- Gatekeeper Dommel does not have a loot template.
    http://camelot.allakhazam.com/db/search.html?cmob=3071

- Grand Chancellor Adremal does not have a loot template.
    http://camelot.allakhazam.com/db/search.html?cmob=3049

- Demoniac Familiar does not have a loot template.
    http://camelot.allakhazam.com/db/search.html?cmob=2822

- Apprentice Necyomancer does not have a loot template.
    http://camelot.allakhazam.com/db/search.html?cmob=2821

- Deamhaness does not have a loot template.
    http://camelot.allakhazam.com/db/search.html?cmob=2622

- Necyomancer does not have a loot template.
    http://camelot.allakhazam.com/db/search.html?cmob=2969

- Cursed Necyomancer has a false loot template.
    He would have to drop Sapphire Seals instead of Emerald Seals.
    http://camelot.allakhazam.com/db/search.html?cmob=3585

- Soultorn Norse Flammen Herra does not have a loot template.
    http://camelot.allakhazam.com/db/search.html?cmob=3135

- Tormented Necyomancer does not have a loot template.
    http://camelot.allakhazam.com/db/search.html?cmob=3140

- Umbrood Warrior does not have a loot template.
    http://camelot.allakhazam.com/db/search.html?cmob=2960

- Chaosian does not have a loot template.
    Besides, this mob has the wrong model.
    The correct Mob Model ID is: 635
    http://camelot.allakhazam.com/db/search.html?cmob=3016

- The Mob Beliathan is missing completely and i think it need a loot template.
    http://camelot.allakhazam.com/db/search.html?cmob=3014

- Chamberlain does not have a loot template.
    http://camelot.allakhazam.com/db/search.html?cmob=3015

- Soultorn Hibernian Wayfayer does not have a loot template.
    http://camelot.allakhazam.com/db/search.html?cmob=3133

- Soultorn Norse Isen Vakten does not have a loot template.
    http://camelot.allakhazam.com/db/search.html?cmob=2971

- Soultorn Hibernian Wayfayer does not have a loot template.
    http://camelot.allakhazam.com/db/search.html?cmob=3133

- **Many** Inquisitors does not have a loot template.

- **Many**  Earls does not have a loot template.

- **Many**  Chthonic Knights does not have a loot template.

- **Many**  Dukes does not have a loot template.

- **Many**  Marquis does not have a loot template.

**Comment by rogersmith0** [comment]
Showing 13 Chthonian Crawler loaded in the DB - could probably add a few in DF

**Comment by rogersmith0** [comment]
Showing loot template for soultorn hibernian wayfayer in DB already

**Comment by rogersmith0** [comment]
Behomoth may not get added until encounter support in DOLSharp (Legion Encounter) -- Will need researching

**Comment by rogersmith0** [comment]
Everything but Behemoth fixed in PR #122
