### ISSUE TITLE
Training Dummy's in Tutorial zones have wrong class or roaming

### ISSUE THREAD

**Issue by rogersmith0** [Eve-of-Darkness/db-public#129]
- Need to verify all training dummy mobs.  
- Need to correct classes and disable roaming.

**Comment by OntheDOL** [comment]
just noticed this one while having a quick play around
UPDATE `dol`.`mob` SET `Speed`='0' WHERE `ClassType`='DOL.GS.GameTrainingDummy';
UPDATE `dol`.`mob` SET `RoamingRange`='0' WHERE `ClassType`='DOL.GS.GameTrainingDummy';
UPDATE `dol`.`npctemplate` SET `MaxSpeed`='0' WHERE `ClassType`='DOL.GS.GameTrainingDummy';

those work in heidiSQl , dunno what ol Falkie uses

**Comment by PentiumMMX166** [comment]
they are also aggro too when you are PLVL 1 so they will attack you when you're too close to them for too long. and yes, they do hurt you, and the Unyielding and Tough ones have even killed me.

**Comment by Nachtmahr91** [comment]
If the problem has been solved, it can be closed.
