### ISSUE TITLE
Unnecessary Dreaded Seal content

### ISSUE THREAD

**Issue by tegstewart** [Eve-of-Darkness/db-public#17]
Since my Dreaded Seal script populates everything into the DB itself, we don't need any of that nonsense cluttering up the DB and showing up on non-PvE servers.

Here are the queries to clean out all that junk:
DELETE FROM itemtemplate WHERE `Name` LIKE "% dreaded seal";
DELETE FROM mob WHERE guild="Dreaded seal collector";
DELETE FROM `npcequipment` WHERE `TemplateID` IN('6c56259a-5252-43bb-8b79-752e15efa501','371ed47f-3b60-410b-80ed-43d1a89686a7','a3bffa0e-90fa-4fcf-9233-ccd7cebfc533');
DELETE FROM `npctemplate` WHERE `TemplateId` IN (60160825,60163065,60165263);

**Comment by LRFalk01** [comment]
I linked the wrong issue ><, reopening.
