### ISSUE TITLE
/mob copy command doesn't work

### ISSUE THREAD

**Issue by PentiumMMX166** [Eve-of-Darkness/db-public#204]
when i attempt to copy a mob (example: /mob copy cyclops), nothing happens, no error text, nothing.

**Comment by Nachtmahr91** [comment]
The Mob Copy command works without problems. You have to click on a mob first and then you type / mob copy.

**Comment by PentiumMMX166** [comment]
it isn't for me, i have the latest DOL server program, even if i select the mob and do that, the same thing, doesn't work.

**Comment by PentiumMMX166** [comment]
It just doesn't work with mobs that are already in the DB, only works with a mob that i newly created.
