### ISSUE TITLE
Give recastdelay to pet HOTs and similar spells

### ISSUE THREAD

**Issue by tegstewart** [Eve-of-Darkness/db-public#22]
You know that thing where you're playing a necromancer and the client doesn't tell you when the HOT and dmg shield runs out so you know to cast again?  I hate that, so I fixed it by adding recastdelays and causing the client to grey out the spell icon until it's time to cast it again.

For most spells, it's ideal to cast them again right before they expire, so recastdelay = duration - casttime, with any cast time delay refreshing it early.  For HOTs, you always want that last tick to get in, so recastdelay = duration - 1.  Both 2s and 3s spells have a minimum cast time around 1s, so that's the margin we want.  It's better to cast a HOTs 2s late than lose 20% of it's effectiveness casting it too early.

```
UPDATE spell SET recastdelay=14 WHERE duration =15 AND casttime=3 AND recastdelay=0 AND target IN ("self","group","pet") AND pulse=0; # All HOTs
UPDATE spell SET recastdelay=18 WHERE duration =20 AND casttime=2 AND recastdelay=0 AND target IN ("self","group","pet") AND pulse=0; # No HOTs
UPDATE spell SET recastdelay=17 WHERE duration =20 AND casttime=3 AND recastdelay=0 AND target IN ("self","group","pet") AND pulse=0 AND TYPE!='Heal';
UPDATE spell SET recastdelay=19 WHERE duration =20 AND casttime=3 AND recastdelay=0 AND target IN ("self","group","pet") AND pulse=0 AND TYPE='Heal';
UPDATE spell SET recastdelay=27 WHERE duration =30 AND casttime=3 AND recastdelay=0 AND target IN ("self","group","pet") AND pulse=0; # No HOTs
UPDATE spell SET recastdelay=59 WHERE duration =60 AND casttime=3 AND recastdelay=0 AND target IN ("self","group","pet") AND pulse=0; # All HOTs
```

**Comment by OntheDOL** [comment]
hmm this is a fairly custom change no? i feel like this is something that should be left to the individual to decide (custom spells)

**Comment by tegstewart** [comment]
It's something that is already in place for most spells without a cast time.  To withhold it from spells which are already harder to use properly because of a cast time is incredibly poor design.  Is live is like this, then at the risk of sounding harsh they deserve a slap for leaving it that way.  It's one thing to change content that impacts game balance, but this is a GUI change that prevents wasted casts.  If we can improve on the client interface, it seems silly to not do so.

That said, if people don't want to take that step beyond making the DB purely livelike, I could either put this in my custom PvE solo package, or even better do it programmatically within code if a serverproperty is set so the person running the server has the option of turning it on or off.

**Comment by tegstewart** [comment]
Leo mentioned on discord that we already have a precedent for this in the form of quickcast.  DOL displays the quickcast icon as a buff to tell you when it's active, while live forces you to read it in the log to see if the keypress went through.

So, in terms of quickcast, DOL is already better than live in terms of GUI.  I think that's a trend we should continue.

**Comment by tegstewart** [comment]
I'm going to pull this for now.  There may be better ways to do this at the code level that also gives the option of enabling/disabling it with server properties so we aren't forcing people to use it if they don't want to.
