### ISSUE TITLE
Spell Levels

### ISSUE THREAD

**Issue by Scrubtasticx** [Eve-of-Darkness/db-public#220]
On newest compile of DOLserver repo all spells on tooltips say level 1

Combat Skills are showing correctly its just spells

Client 1125. and they work on Los-Ojo's Repo just not offical DOL.

**Comment by LRFalk01** [comment]
What makes you think this is a DB issue?

**Comment by Scrubtasticx** [comment]
Sorry ROFL opened issue on wrong repo and forgot to close it ill do it now :)
