### ISSUE TITLE
DOLconfig.exe

### ISSUE THREAD

**Issue by 723wolf** [Eve-of-Darkness/db-public#225]
Dolconfig.exe in the auto-builder seems to not be working with the newest release. I had to download an older release to get it working.

**Comment by NetDwarf** [comment]
This belongs to Dawn-of-Light/DOLSharp. However I think I found the culprit.

For a quick bandaid in serverconfig.xml you can just replace:
`<ScriptAssemblies />`
with
`<ScriptAssemblies> </ScriptAssemblies>`

**Comment by LRFalk01** [comment]
Thanks @NetDwarf. I agree this is not an issue for this DB project. Closing issue.

**Comment by NetDwarf** [comment]
Should be fixed with Dawn-of-Light/DOLSharp#331.
