### ISSUE TITLE
New Serverproperty

### ISSUE THREAD

**Issue by tegstewart** [Eve-of-Darkness/db-public#23]
Because I despise waiting to log out.  :-)

INSERT INTO serverproperty (Category,Key,Description,DefaultValue,Value) VALUES ('server','remove_quit_timer','Allow players to log out without waiting?','false','false');

**Comment by tegstewart** [comment]
INSERT INTO serverproperty (Category,Key,Description,DefaultValue,Value) VALUES ('account','remove quit timer','Allow players to log out without waiting?','false','false');

It should be lowercase to match other properties.

**Comment by tegstewart** [comment]
Grrr...  They use _ instead of spaces as well.

INSERT INTO serverproperty (Category,Key,Description,DefaultValue,Value) VALUES ('account','remove_quit_timer','Allow players to log out without waiting?','false','false');

**Comment by LRFalk01** [comment]
Updated original comment w/ final query.

**Comment by tegstewart** [comment]
It is pulled, and I am happy.  :-)
