### ISSUE TITLE
Missing install instruction

### ISSUE THREAD

**Issue by DigitalBox98** [Eve-of-Darkness/db-public#249]
Go software is not enough to build the "public-db.sql".
Indeed for Win10 you need to install in addition to Go, the TDM-GCC package : https://jmeubank.github.io/tdm-gcc/

Once installed the command "go run . -export mysql" is working fine without any error

**Comment by NetDwarf** [comment]
Are the new instructions working on Windows?

**Comment by DigitalBox98** [comment]
Only once the TDM-GCC package is installed under windows 10 :) 
On MacOS no need for this package and working fine.

**Comment by NetDwarf** [comment]
Even with the new binary release?

**Comment by DigitalBox98** [comment]
Ah... not tested with the new binary, so I don't know.

**Comment by DigitalBox98** [comment]
With public-db-tools binary, yes it's working fine without the need for TDM-GCC package
