### ISSUE TITLE
More renegade armspeople

### ISSUE THREAD

**Issue by tegstewart** [Eve-of-Darkness/db-public#25]
The issue with mobs using keep brains and classtypes is also present in Hibernia and Albion regions.  There may even be a few ranged nukers, which would kill instakill anybody that got within 2k range of them.  :-)

Here's the query to fix them:
UPDATE `Mob` SET `ClassType`='DOL.GS.GameGuard', `Brain`='DOL.AI.Brain.GuardBrain', `NPCTemplateID`=NULL 
WHERE region IN (1,200) AND classtype LIKE "dol.gs.keeps.%";

And getting rid of the weird sniper wizard:
DELETE FROM `Mob` WHERE `Mob_ID`='100031149';

**Comment by LRFalk01** [comment]
I have a concern that 3 of the hib guards are in an RvR zone or boarding an RvR zone (Lough Derg and
Mount Collory). Do you think these should be updated? None of the other ones are in an RvR zone, so they are probably safe to lobotomize.

**Comment by tegstewart** [comment]
The two in Lough Derg are on the path S of Tir na mbeo.  They're the ones who one-shotted me while I was taking a horse path.  :-)

There are tons of guards in front of the gates.  Pretty sure a lot more than on live, so I don't think they'll be a concern.
