### ISSUE TITLE
Move slow mobs

### ISSUE THREAD

**Issue by tegstewart** [Eve-of-Darkness/db-public#35]
My query last time fixed speeds in MOB, but didn't do anything about slow speeds in NPCTemplate.

`UPDATE `NpcTemplate` SET `MaxSpeed`=180 WHERE `MaxSpeed` < 180;`

**Comment by LRFalk01** [comment]
A good number of these are merchants. Are there any concerns w/ updating the speed of non player enemies?

**Comment by tegstewart** [comment]
We could probably limit it to classtype 'DOL.GS.GameNPC','', and NULL.

If we want to get really fancy, we could do an inner join and only get region 0 as well.

**Comment by LRFalk01** [comment]
Can you get a more accurate query? I have the following which lowers it to about 700 records being edited:
WHERE MaxSpeed < 180 AND ClassType = 'DOL.GS.GameNPC' AND GuildName = '';

**Comment by tegstewart** [comment]
This one brings it down to 496.

UPDATE NpcTemplate, Mob SET NpcTemplate.MaxSpeed=180 WHERE
    `Mob`.`NPCTemplateID`=`NpcTemplate`.`TemplateId` AND `Mob`.`Realm`=0 AND NpcTemplate.MaxSpeed<180;

**Comment by LRFalk01** [comment]
Boom. I am confirm with this. I'll get it in today

**Comment by tegstewart** [comment]
I guess if you really want to be picky, we could roll back to before the previous speed change in mob and do this instead:
UPDATE NpcTemplate, Mob SET Mob.Speed=180 WHERE
Mob.NPCTemplateID=NpcTemplate.TemplateId AND Mob.Realm=0 AND NpcTemplate.MaxSpeed<180;
