### ISSUE TITLE
Lots of 0 price items

### ISSUE THREAD

**Issue by tegstewart** [Eve-of-Darkness/db-public#53]
There are a whole bunch of items with 0 prices that shouldn't be.  So I tried to figure out a formula that approximates equipment prices properly, and did up two queries to fix it.

UPDATE ItemTemplate SET Price=(0.12*`Level`*`Level`*`Level`) WHERE Price = 0 AND `Level` >= 10 AND Object_Type < 42 AND MaxCount > 1;
UPDATE ItemTemplate SET Price=(12*`Level`*`Level`*`Level`) WHERE Price = 0 AND `Level` > 10 AND Object_Type < 42;

**Comment by LRFalk01** [comment]
I don't really agree with this. It feels like replacing missing data with dirty data. I'll try to investigate the item dump Broadsword did.

**Comment by tegstewart** [comment]
Sounds good to me.  This is a placeholder, but it might be better to keep the 0 prices to make it easier to identify items missing data.
