### ISSUE TITLE
Thane Polar Rift spell OP

### ISSUE THREAD

**Issue by tegstewart** [Eve-of-Darkness/db-public#58]
The Thane Polar rift spell currently does 75 damage when it should be 45.  As a result, you get more damage speccing a Thane to 34 sword and use Polar Rift than to spec axe to 50 and use Tyr's Fury.  Definitely not right.

UPDATE Spell SET Damage=45 WHERE SpellID=21112;

**Comment by LRFalk01** [comment]
I agree with your assessment.
