### ISSUE TITLE
Housing Hookpoint Teleporter

### ISSUE THREAD

**Issue by Nachtmahr91** [Eve-of-Darkness/db-public#69]
When you stand in the house and buy a hookpoint teleporter, then you can buy teleporter for all realms.

http://www.directupload.net/file/d/4942/vp829ee2_jpg.htm

**Comment by LRFalk01** [comment]
This is not really an issue with the DB per say. It's more of an issue with how HouseTemplateMgr is setup. When rendering eMerchantWindowType.HousingNPCHookpoint merchant window, it does not have different merchant lists per realm. Fixing this would require a code change. The code change would render some of the existing data invalid. I think HouseTemplateMgr.IndoorNPCShopItems would need to become a merchant list per realm. Then a 4th list that has all of these I guess for pvp/pve servers.

**Comment by LRFalk01** [comment]
Not a DB issue. PR'd DOL with fix: https://github.com/Dawn-of-Light/DOLSharp/pull/127
