### ISSUE TITLE
Duplicate characters in keeps

### ISSUE THREAD

**Issue by tegstewart** [Eve-of-Darkness/db-public#77]
The current keep position table doesn't include height data.  Running keepposition.sql from [http://www.dolserver.net/download/file.php?id=3550](http://www.dolserver.net/download/file.php?id=3550) will remedy that.

Then we need to clean out some junk entries and assign consistent templateids to guard lords, keep hasteners, and mission masters.

DELETE FROM KeepComponent WHERE Heading < 0;
DELETE FROM KeepPosition WHERE Classtype="DOL.GS.Keeps.GuardChampion";

UPDATE KeepPosition SET TemplateID="0811d9b7-03e4-4a00-babf-6f58d1e8b1b9" WHERE ClassType="DOL.GS.Keeps.FrontierHastener";
UPDATE KeepPosition SET TemplateID="24e9a2f4-8523-499b-bfae-ad5e797526c0" WHERE ClassType="DOL.GS.Keeps.FrontiersPortalStone";
UPDATE KeepPosition SET TemplateID="3ab163f0-3b3f-4ca6-8804-40e2db32c77b" WHERE ClassType="DOL.GS.Keeps.GuardLord";
UPDATE KeepPosition SET TemplateID="6b1ae7a4-0f78-44cb-8aa3-ee0249e29e92" WHERE ClassType="DOL.GS.Keeps.MissionMaster";

There's a lot more going on in keepposition that bears looking at, but this is a good start.

**Comment by tegstewart** [comment]
While we're here, this gets rid of the keep doors that keep throwing errors.  Their location is WAY off the grid, which I think is leading to it being impossible to instantiate them in the encapsulating keeparea.

DELETE FROM keepposition WHERE keepposition_id IN ("3ede3538-9e0c-43a1-b7c0-f5565d0fed70","3cb8a46c-7ac0-4511-a8e9-a782ad79fe41");

**Comment by LRFalk01** [comment]
Can you update this with what you want done. Your 'scratch that' is leaving me confused.

**Comment by tegstewart** [comment]
I had a SQL statement to delete a few doors that weren't being loaded properly, but that didn't actually resolve the issue.  I should have left the original comment there for context.

All the statements above are good to go, we just have to update the keepposition table from dolpub first as it adds height data.

**Comment by tegstewart** [comment]
Closing this as I'm adding it as a pull instead.
