### ISSUE TITLE
Housing Bug (Server Crash)

### ISSUE THREAD

**Issue by Nachtmahr91** [Eve-of-Darkness/db-public#93]
If I want to buy a house in the Housing Zone and want to set it up, my DOLServer.exe hangs up and closes the program.

[RegionTime1] - ERROR - DOL.GS.GameTimer+TimeManager - Timer callback (DOL.GS.PacketHandler.Client.v168.DialogResponseHandler+DialogBoxResponseAction tick:0x00073D9E interval:0 manager:'RegionTime1' actionSource: (DOL.GS.GamePlayer name=Test DB_ID=863cd87b-afde-480f-88f5-9c84187659e1 oid=1145 state=Active reg=2 loc=572246,565029,3520 class=Armsman(2)))
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei DOL.GS.Housing.House.set_X(Int32 value) in D:\Server Eve of Darkness\GameServer\housing\House.cs:Zeile 263.
   bei DOL.GS.Point2D..ctor(Int32 x, Int32 y) in D:\Server Eve of Darkness\GameServer\world\Point2D.cs:Zeile 63.
   bei DOL.GS.Point3D..ctor() in D:\Server Eve of Darkness\GameServer\world\Point3D.cs:Zeile 31.
   bei DOL.GS.Housing.House..ctor(DBHouse house) in D:\Server Eve of Darkness\GameServer\housing\House.cs:Zeile 296.
   bei DOL.GS.Housing.GameLotMarker.CreateHouse(GamePlayer player, Int32 model) in D:\Server Eve of Darkness\GameServer\housing\LotMarker.cs:Zeile 216.
   bei DOL.GS.Housing.GameLotMarker.BuyLot(GamePlayer player, Byte response) in D:\Server Eve of Darkness\GameServer\housing\LotMarker.cs:Zeile 126.
   bei DOL.GS.PacketHandler.Client.v168.DialogResponseHandler.DialogBoxResponseAction.OnTick() in D:\Server Eve of Darkness\GameServer\packets\Client\168\DialogResponseHandler.cs:Zeile 119.
   bei DOL.GS.GameTimer.TimeManager.TimeThread() in D:\Server Eve of Darkness\GameServer\gameutils\GameTimer.cs:Zeile 917.
2018-01-04 20:23:19,171 - [2] - FATAL - DOL.GS.GameServer - Unhandled exception!
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei DOL.GS.Housing.House.get_HouseNumber() in D:\Server Eve of Darkness\GameServer\housing\House.cs:Zeile 47.
   bei DOL.GS.Housing.House.Finalize() in D:\Server Eve of Darkness\GameServer\housing\House.cs:Zeile 308.

**Comment by LRFalk01** [comment]
This is a regression in EOD caused by my trying to roll up all of the packet code. This is not an issue with the database
