### ISSUE TITLE
Missing Darkness Falls Mobs

### ISSUE THREAD

**Issue by Nachtmahr91** [Eve-of-Darkness/db-public#99]
In Darkness Falls important mobs like "Legion", "Gatekeeper Dommel", "Highlords" and many more are missing,

**Comment by LRFalk01** [comment]
ToA is not missing all mobs and NPCs. probably most. but it is the 2nd most populated expansion in the mob table.

**Comment by LRFalk01** [comment]
@rogersmith0 Checked in several DF fixes. Closing issue.
